version: "3.9"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - kwu_api_readingroom_db:/var/lib/mysql

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - kwu_api_readingroom

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - kwu_api_readingroom

  readingroom_crawler:
    build: 
      context: ./readingroom_crawler
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - kwu_api_readingroom

volumes:
  kwu_api_readingroom_db:
    external: true

networks:
  kwu_api_readingroom:
    driver: bridge