version: "3.9"

services:
  mongodb:
    volumes:
      - kwu_api_readingroom_db:/data/db
    image: mongo
    container_name: mongodb
    restart: always
    # ports:
    #   - "27017:27017"
    command: --quiet
    networks:
      - kwu_api_readingroom

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:80
    depends_on:
      - backend
    networks:
      - kwu_api_readingroom

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - kwu_api_readingroom

  readingroom_crawler:
    build: 
      context: ./readingroom_crawler
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - kwu_api_readingroom

volumes:
  kwu_api_readingroom_db:
    external: true

networks:
  kwu_api_readingroom:
    driver: bridge